language: objective-c
osx_image: xcode9
xcode_workspace: 战旗TV/战旗TV.xcworkspace
xcode_scheme: 战旗TV
script:
    - xcodebuild clean build -sdk iphonesimulator -workspace 战旗TV.xcworkspace -scheme 战旗TV CODE_SIGNING_REQUIRED=NO